version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: admin
         POSTGRES_DB: starbucksdb
    
